//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatMes.Client.Entity.batmes_client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class batmes_client_entity : DbContext
    {
        public batmes_client_entity()
            : base("name=batmes_client_entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<battery> battery { get; set; }
        public virtual DbSet<battery_result_code> battery_result_code { get; set; }
        public virtual DbSet<cell> cell { get; set; }
        public virtual DbSet<func> func { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<ops> ops { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_func> role_func { get; set; }
        public virtual DbSet<station> station { get; set; }
        public virtual DbSet<station_cell> station_cell { get; set; }
        public virtual DbSet<sys_event> sys_event { get; set; }
        public virtual DbSet<sys_para> sys_para { get; set; }
        public virtual DbSet<sys_para_sort> sys_para_sort { get; set; }
        public virtual DbSet<timed_task> timed_task { get; set; }
        public virtual DbSet<tray_map> tray_map { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_log> user_log { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
