//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatMes.Client.Entity.batmes_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class station
    {
        public string station_id { get; set; }
        public string name { get; set; }
        public int type { get; set; }
        public int location { get; set; }
        public string remark { get; set; }
        public bool is_disable { get; set; }
        public bool is_lock_fire { get; set; }
        public bool is_lock_real { get; set; }
        public int real_fail_times { get; set; }
        public int status { get; set; }
        public System.DateTime status_time { get; set; }
    }
}
