//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatMes.Client.Entity.batmes_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class timed_task
    {
        public string task_id { get; set; }
        public int task_status { get; set; }
        public string tray_code { get; set; }
        public int cell_id { get; set; }
        public Nullable<int> processes { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime last_update_time { get; set; }
    }
}
