//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatMes.Client.Entity.batmes_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_log
    {
        public int log_id { get; set; }
        public int user_id { get; set; }
        public int func_id { get; set; }
        public int ops_type { get; set; }
        public string cont { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
