//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatMes.Client.Entity.batmes_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string account { get; set; }
        public string pswd { get; set; }
        public string name { get; set; }
        public int gender { get; set; }
        public string tel { get; set; }
        public string im { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public int login_count { get; set; }
        public int status { get; set; }
        public System.DateTime status_time { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
